import Link from "next/link";
import { notFound } from "next/navigation";
import { DemoBanner, PageHeader, StatusBadge, buttonClass, formatDate, panelClass, titleCase } from "@/components/domain/argus-ui";
import { demoBriefs, demoEvents } from "@/packages/shared/demo-data";

export function generateStaticParams() { return demoBriefs.map((brief) => ({ slug: brief.slug })); }

export default async function BriefPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const brief = demoBriefs.find((item) => item.slug === slug);
  if (!brief) notFound();
  const eventById = new Map(demoEvents.map((event) => [event.id, event]));
  const sections = [
    ["Regional developments", brief.regionalDevelopments], ["Watchlist activity", brief.watchlistActivity], ["Escalation risks", brief.escalationRisks], ["Confidence changes", brief.confidenceChanges], ["Disputed reporting", brief.disputedReporting], ["Events requiring review", brief.eventsRequiringReview], ["Resolved events", brief.resolvedEvents],
  ] as const;
  return <main className="route-page page-stack space-y-5 p-4 sm:p-6 xl:p-8"><DemoBanner /><div><Link href="/briefs" className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-500 hover:text-cyan-200">← Intelligence briefs</Link></div><PageHeader eyebrow={`${titleCase(brief.type)} brief / ${brief.id.toUpperCase()}`} title={brief.title} description={`Coverage: ${formatDate(brief.periodStart, false)} — ${formatDate(brief.periodEnd, false)} · Generated ${formatDate(brief.generatedAt)}`} actions={<><StatusBadge tone="violet">{brief.generatedBy}-generated</StatusBadge><StatusBadge tone={brief.status === "published" ? "green" : "amber"}>{brief.status}</StatusBadge><Link href="/aether?mode=brief-generation" className={buttonClass}>Refine in Aether</Link></>} />
    <article className="brief-report mx-auto w-full max-w-6xl overflow-hidden rounded-xl border border-white/10 bg-[#101820]/95 shadow-[0_30px_90px_rgba(0,0,0,.28)]">
      <header className="border-b border-white/[.08] bg-[radial-gradient(circle_at_85%_0%,rgba(34,211,238,.09),transparent_33%)] p-6 sm:p-9"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-cyan-300/70">ARGUS intelligence product</p><p className="mt-2 text-[10px] text-slate-500">Analysis and Reporting of Global Unfolding Situations</p></div><div className="text-right font-mono text-[9px] uppercase leading-5 text-slate-600"><p>Classification: Demonstration</p><p>Distribution: Personal workspace</p></div></div><h2 className="mt-10 text-2xl font-semibold leading-9 text-slate-50 sm:text-3xl">Executive summary</h2><p className="mt-4 max-w-4xl text-base leading-8 text-slate-300">{brief.executiveSummary}</p></header>
      <div className="space-y-10 p-6 sm:p-9">
        <section><div className="mb-5 flex items-center gap-3"><span className="font-mono text-[10px] text-cyan-300/60">01</span><h2 className="text-lg font-semibold text-slate-100">Priority developments</h2><span className="h-px flex-1 bg-white/[.07]" /></div><div className="grid gap-4 lg:grid-cols-2">{brief.priorityDevelopments.map((development) => { const event = eventById.get(development.eventId); return <div key={development.eventId} className="rounded-lg border border-white/[.08] bg-white/[.018] p-5"><div className="flex items-center justify-between gap-3"><StatusBadge tone={development.confidence >= 80 ? "green" : "amber"}>{development.confidence}% confidence</StatusBadge>{event && <span className="text-[9px] uppercase tracking-[.12em] text-slate-600">Severity {event.severity}</span>}</div><h3 className="mt-4 text-sm font-semibold leading-6 text-slate-200">{development.headline}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{development.assessment}</p>{event && <div className="mt-4"><Link href={`/events/${event.slug}`} className="text-[10px] font-semibold text-cyan-200">Open evidence dossier →</Link></div>}</div>; })}</div></section>
        {sections.map(([title, entries], sectionIndex) => entries.length > 0 && <section key={title}><div className="mb-5 flex items-center gap-3"><span className="font-mono text-[10px] text-cyan-300/60">{String(sectionIndex + 2).padStart(2, "0")}</span><h2 className="text-lg font-semibold text-slate-100">{title}</h2><span className="h-px flex-1 bg-white/[.07]" /></div><div className="grid gap-4 md:grid-cols-2">{entries.map((entry) => <div key={entry.id} className={`${panelClass} p-5`}><h3 className="text-sm font-semibold text-slate-200">{entry.title}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{entry.summary}</p>{entry.items.length > 0 && <ul className="mt-4 space-y-2">{entry.items.map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-400"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-cyan-300" />{item}</li>)}</ul>}</div>)}</div></section>)}
        <section><div className="mb-5 flex items-center gap-3"><span className="font-mono text-[10px] text-cyan-300/60">09</span><h2 className="text-lg font-semibold text-slate-100">Collection gaps</h2><span className="h-px flex-1 bg-white/[.07]" /></div><ul className="grid gap-3 md:grid-cols-2">{brief.collectionGaps.map((gap) => <li key={gap} className="rounded-lg border border-amber-300/10 bg-amber-300/[.025] p-4 text-xs leading-5 text-slate-400">{gap}</li>)}</ul></section>
        <section className="rounded-xl border border-violet-300/15 bg-violet-300/[.035] p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-slate-100">Aether analysis</h2><StatusBadge tone="violet">AI-generated</StatusBadge></div><p className="mt-4 text-sm leading-7 text-slate-300">{brief.aetherAnalysis}</p><p className="mt-5 text-[9px] uppercase tracking-[.13em] text-slate-600">Generated from stored demonstration evidence only · Verify against linked dossiers before action</p></section>
      </div>
    </article>
  </main>;
}
