/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=wrangler.jsonc --include-runtime=false cloudflare-env.d.ts` (hash: 39d5875b5e7b74f55266de4ae7e51d35)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGINS: "https://thunderrock424242.github.io,http://localhost:5173,http://127.0.0.1:5173";
	AUTH_CALLBACK_URL: "https://thunderrock424242.github.io/ARGUS/";
	AUTH_SESSION_TTL_SECONDS: "28800";
	ARGUS_DEMO_ENABLED: "false";
	COLLECTOR_PILOT_ENABLED: "true";
	COLLECTOR_USGS_ENABLED: "true";
	COLLECTOR_GUARDIAN_ENABLED: "true";
	COLLECTOR_X_ENABLED: "false";
	COLLECTOR_GUARDIAN_QUERY: "world";
	COLLECTOR_X_QUERY: "(earthquake OR wildfire OR cyclone OR flood) lang:en -is:retweet";
	ORBITAL_LIVE_ENABLED: "false";
	ORBITAL_CELESTRAK_ENABLED: "true";
	ORBITAL_JPL_ENABLED: "true";
	ORBITAL_DONKI_ENABLED: "true";
	RETENTION_DAYS: "180";
	ARGUS_ADMIN_TOKEN: string;
	GITHUB_OAUTH_CLIENT_ID: string;
	GITHUB_OAUTH_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "AUTH_CALLBACK_URL" | "AUTH_SESSION_TTL_SECONDS" | "ARGUS_DEMO_ENABLED" | "COLLECTOR_PILOT_ENABLED" | "COLLECTOR_USGS_ENABLED" | "COLLECTOR_GUARDIAN_ENABLED" | "COLLECTOR_X_ENABLED" | "COLLECTOR_GUARDIAN_QUERY" | "COLLECTOR_X_QUERY" | "ORBITAL_LIVE_ENABLED" | "ORBITAL_CELESTRAK_ENABLED" | "ORBITAL_JPL_ENABLED" | "ORBITAL_DONKI_ENABLED" | "RETENTION_DAYS" | "ARGUS_ADMIN_TOKEN" | "GITHUB_OAUTH_CLIENT_ID" | "GITHUB_OAUTH_CLIENT_SECRET">> {}
}
