/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false cloudflare-env.d.ts` (hash: a6d632b6ccfbc7aad06837633f0d78ad)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGINS: "https://thunderrock424242.github.io,http://localhost:5173,http://127.0.0.1:5173";
	AUTH_CALLBACK_URL: "https://thunderrock424242.github.io/ARGUS/";
	AUTH_SESSION_TTL_SECONDS: "28800";
	RETENTION_DAYS: "180";
	ARGUS_ADMIN_TOKEN: string;
	GITHUB_OAUTH_CLIENT_ID: string;
	GITHUB_OAUTH_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "AUTH_CALLBACK_URL" | "AUTH_SESSION_TTL_SECONDS" | "RETENTION_DAYS" | "ARGUS_ADMIN_TOKEN" | "GITHUB_OAUTH_CLIENT_ID" | "GITHUB_OAUTH_CLIENT_SECRET">> {}
}
