"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { IntelligenceBrief } from "@/packages/shared/types";
import { StatusBadge, buttonClass, controlClass, formatDate, titleCase } from "@/components/domain/argus-ui";

export function BriefsIndex({ briefs }: { briefs: IntelligenceBrief[] }) {
  const [type, setType] = useState("all");
  const [query, setQuery] = useState("");
  const visible = useMemo(() => briefs.filter((brief) => (type === "all" || brief.type === type) && (!query.trim() || `${brief.title} ${brief.executiveSummary}`.toLowerCase().includes(query.toLowerCase()))), [briefs, query, type]);
  const featured = visible[0];
  return (
    <section className="space-y-4">
      <div className="toolbar grid gap-3 rounded-xl border border-white/10 bg-[#101820]/90 p-3 md:grid-cols-[1fr_190px]"><label className="relative"><span className="sr-only">Search briefs</span><input className={`${controlClass} w-full pl-9`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search briefs and assessments…" /><span className="absolute left-3 top-2.5 text-slate-500">⌕</span></label><select className={controlClass} aria-label="Brief type" value={type} onChange={(event) => setType(event.target.value)}><option value="all">All brief types</option><option value="daily">Daily brief</option><option value="weekly">Weekly assessment</option><option value="custom">Custom brief</option></select></div>
      {featured && <article className="relative overflow-hidden rounded-xl border border-cyan-300/15 bg-[#101b24] p-6 shadow-[0_24px_70px_rgba(0,0,0,.25)] lg:p-8"><div className="pointer-events-none absolute -right-20 -top-24 h-80 w-80 rounded-full border border-cyan-300/[.07] shadow-[inset_0_0_80px_rgba(103,232,249,.03)]" /><div className="relative grid gap-8 lg:grid-cols-[minmax(0,1.25fr)_minmax(280px,.75fr)]"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge tone="violet">{featured.generatedBy}-generated</StatusBadge><StatusBadge tone={featured.status === "published" ? "green" : "amber"}>{featured.status}</StatusBadge><span className="text-[9px] uppercase tracking-[.15em] text-slate-500">{titleCase(featured.type)} intelligence brief</span></div><h2 className="mt-5 max-w-3xl text-2xl font-semibold leading-9 text-slate-50">{featured.title}</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">{featured.executiveSummary}</p><div className="mt-6 flex flex-wrap items-center gap-3"><Link href={`/briefs/${featured.slug}`} className={`${buttonClass} border-cyan-300/30 bg-cyan-300/10 text-cyan-100`}>Read full brief →</Link><span className="text-[10px] text-slate-500">Coverage {formatDate(featured.periodStart, false)} — {formatDate(featured.periodEnd, false)}</span></div></div><div className="rounded-lg border border-white/[.08] bg-black/15 p-4"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">Priority developments</p><ol className="mt-3 space-y-3">{featured.priorityDevelopments.slice(0, 3).map((item, index) => <li key={item.eventId} className="grid grid-cols-[24px_1fr_auto] gap-3 border-b border-white/[.06] pb-3 last:border-0 last:pb-0"><span className="font-mono text-[10px] text-cyan-300/70">0{index + 1}</span><div><p className="text-xs font-semibold leading-5 text-slate-200">{item.headline}</p><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-500">{item.assessment}</p></div><span className="font-mono text-[9px] text-slate-500">{item.confidence}%</span></li>)}</ol></div></div></article>}
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.slice(1).map((brief) => <article key={brief.id} className="panel flex min-h-72 flex-col rounded-xl border border-white/10 bg-[#101820]/90 p-5"><div className="flex items-center justify-between gap-3"><StatusBadge tone={brief.type === "weekly" ? "cyan" : brief.type === "custom" ? "amber" : "violet"}>{brief.type}</StatusBadge><span className="text-[9px] uppercase tracking-[.13em] text-slate-600">{brief.generatedBy}</span></div><h2 className="mt-5 text-base font-semibold leading-6 text-slate-100">{brief.title}</h2><p className="mt-3 line-clamp-4 text-xs leading-5 text-slate-400">{brief.executiveSummary}</p><dl className="mt-5 grid grid-cols-3 gap-2"><div><dt className="text-[8px] uppercase tracking-[.11em] text-slate-600">Priority</dt><dd className="mt-1 font-mono text-xs text-slate-300">{brief.priorityDevelopments.length}</dd></div><div><dt className="text-[8px] uppercase tracking-[.11em] text-slate-600">Regions</dt><dd className="mt-1 font-mono text-xs text-slate-300">{brief.regionalDevelopments.length}</dd></div><div><dt className="text-[8px] uppercase tracking-[.11em] text-slate-600">Gaps</dt><dd className="mt-1 font-mono text-xs text-slate-300">{brief.collectionGaps.length}</dd></div></dl><div className="mt-auto flex items-end justify-between gap-3 border-t border-white/[.06] pt-4"><span className="text-[9px] leading-4 text-slate-600">{formatDate(brief.periodStart, false)} —<br />{formatDate(brief.periodEnd, false)}</span><Link href={`/briefs/${brief.slug}`} className="text-xs font-semibold text-cyan-200 hover:text-cyan-100">Open report →</Link></div></article>)}</div>
      {visible.length === 0 && <div className="rounded-xl border border-dashed border-white/10 p-12 text-center text-sm text-slate-500">No intelligence briefs match this search.</div>}
    </section>
  );
}
