"use client";

import { useState } from "react";
import { StatusBadge, buttonClass, controlClass, primaryButtonClass } from "@/components/domain/argus-ui";

function Toggle({ checked, onChange, label, description }: { checked: boolean; onChange: (value: boolean) => void; label: string; description: string }) {
  return <div className="flex items-start justify-between gap-5 py-4"><div><p className="text-sm font-medium text-slate-200">{label}</p><p className="mt-1 max-w-xl text-xs leading-5 text-slate-500">{description}</p></div><button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative mt-1 h-6 w-11 shrink-0 rounded-full transition ${checked ? "bg-cyan-300/30" : "bg-slate-700"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-slate-100 transition ${checked ? "left-6" : "left-1"}`} /></button></div>;
}

export function SettingsConsole() {
  const [section, setSection] = useState("workspace");
  const [saved, setSaved] = useState(false);
  const [compact, setCompact] = useState(true);
  const [reducedMotion, setReducedMotion] = useState(false);
  const [utcPrimary, setUtcPrimary] = useState(true);
  const [desktopAlerts, setDesktopAlerts] = useState(true);
  const [criticalOnly, setCriticalOnly] = useState(false);
  const [autoReview, setAutoReview] = useState(true);
  const [aetherCitations, setAetherCitations] = useState(true);
  const [confidenceThreshold, setConfidenceThreshold] = useState(70);
  const [retention, setRetention] = useState("365");
  const sections = ["workspace", "notifications", "intelligence", "aether", "security", "data"];
  function save() { setSaved(true); window.setTimeout(() => setSaved(false), 1800); }
  return <section className="settings-layout grid gap-4 xl:grid-cols-[220px_minmax(0,1fr)]">
    <nav className="rounded-xl border border-white/10 bg-[#0f1821] p-3 xl:self-start" aria-label="Settings sections"><p className="mb-3 px-2 text-[9px] font-bold uppercase tracking-[.16em] text-slate-600">Configuration</p><div className="grid gap-1 sm:grid-cols-3 xl:grid-cols-1">{sections.map((item) => <button key={item} type="button" className={`min-h-11 rounded-md px-3 text-left text-xs font-semibold transition ${section === item ? "bg-cyan-300/[.07] text-cyan-100 shadow-[inset_3px_0_0_rgba(103,232,249,.65)]" : "text-slate-500 hover:bg-white/[.03] hover:text-slate-300"}`} onClick={() => setSection(item)}>{item.charAt(0).toUpperCase() + item.slice(1)}</button>)}</div><div className="mt-5 border-t border-white/[.06] px-2 pt-4"><StatusBadge tone="green">Local workspace</StatusBadge><p className="mt-3 text-[9px] leading-4 text-slate-600">Settings are device-local in the demonstration build.</p></div></nav>
    <div className="overflow-hidden rounded-xl border border-white/10 bg-[#101820]/90">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[.08] px-5 py-4 sm:px-6"><div><p className="text-[9px] uppercase tracking-[.15em] text-cyan-300/60">{section} preferences</p><h2 className="mt-1 text-lg font-semibold text-slate-100">{section.charAt(0).toUpperCase() + section.slice(1)}</h2></div><div className="flex items-center gap-2"><button type="button" className={buttonClass} onClick={() => window.location.reload()}>Reset</button><button type="button" className={primaryButtonClass} onClick={save}>{saved ? "Saved ✓" : "Save changes"}</button></div></header>
      <div className="p-5 sm:p-6">
        {section === "workspace" && <div className="divide-y divide-white/[.06]"><Toggle checked={compact} onChange={setCompact} label="Compact information density" description="Use tighter table rows and panel spacing for high-density desktop operations." /><Toggle checked={reducedMotion} onChange={setReducedMotion} label="Reduce interface motion" description="Disable developing-event pulses and non-essential transitions while preserving status cues." /><Toggle checked={utcPrimary} onChange={setUtcPrimary} label="Use UTC as primary time" description="Display UTC first across events, briefs, collector runs, and audit records." /><div className="grid gap-4 py-5 md:grid-cols-2"><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Default landing route</span><select className={`${controlClass} w-full`} defaultValue="command"><option value="command">Command Center</option><option value="map">Global Map</option><option value="events">Events</option><option value="review">Review Queue</option></select></label><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Local time zone</span><select className={`${controlClass} w-full`} defaultValue="America/New_York"><option>America/New_York</option><option>Europe/London</option><option>Asia/Singapore</option><option>Australia/Sydney</option></select></label></div></div>}
        {section === "notifications" && <div className="divide-y divide-white/[.06]"><Toggle checked={desktopAlerts} onChange={setDesktopAlerts} label="In-app operational alerts" description="Show source failures, critical watchlist matches, and high-severity review tasks in the notification center." /><Toggle checked={criticalOnly} onChange={setCriticalOnly} label="Critical events only" description="Suppress routine event alerts unless severity is 5 or an analyst marks the event priority." /><div className="grid gap-4 py-5 md:grid-cols-2"><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Digest cadence</span><select className={`${controlClass} w-full`} defaultValue="hourly"><option value="immediate">Immediate</option><option value="hourly">Hourly digest</option><option value="daily">Daily digest</option></select></label><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Quiet hours</span><input className={`${controlClass} w-full`} defaultValue="23:00–06:00 local" /></label></div></div>}
        {section === "intelligence" && <div className="divide-y divide-white/[.06]"><Toggle checked={autoReview} onChange={setAutoReview} label="Automatically route risk signals" description="Send high-severity unverified events, contradictions, possible duplicates, and source failures to review queues." /><div className="py-5"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-slate-200">Default confidence threshold</p><p className="mt-1 text-xs text-slate-500">Threshold for high-confidence filters and watchlist notifications.</p></div><span className="font-mono text-sm text-cyan-200">{confidenceThreshold}%</span></div><input className="mt-4 w-full accent-cyan-300" type="range" min="25" max="95" step="5" value={confidenceThreshold} onChange={(event) => setConfidenceThreshold(Number(event.target.value))} /></div><div className="grid gap-4 py-5 md:grid-cols-2"><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Default correlation radius</span><select className={`${controlClass} w-full`} defaultValue="25"><option value="10">10 km</option><option value="25">25 km</option><option value="50">50 km</option><option value="100">100 km</option></select></label><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Developing-event recheck</span><select className={`${controlClass} w-full`} defaultValue="60"><option value="30">Every 30 minutes</option><option value="60">Hourly</option><option value="180">Every 3 hours</option></select></label></div></div>}
        {section === "aether" && <div className="divide-y divide-white/[.06]"><Toggle checked={aetherCitations} onChange={setAetherCitations} label="Require evidence citations" description="Block Aether responses from rendering as complete when no stored report citations can be resolved." /><Toggle checked={true} onChange={() => undefined} label="Label AI-generated analysis" description="Keep the AI-generated label visible in chat, dossiers, briefs, and review recommendations." /><div className="grid gap-4 py-5 md:grid-cols-2"><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Provider</span><select className={`${controlClass} w-full`} disabled><option>Deterministic local provider</option></select></label><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Default mode</span><select className={`${controlClass} w-full`} defaultValue="event"><option value="event">Event context</option><option value="chat">General analysis</option><option value="compare">Source comparison</option></select></label></div><div className="rounded-lg border border-violet-300/10 bg-violet-300/[.025] p-4 text-xs leading-5 text-slate-500">A real provider can be added server-side through the Aether provider abstraction. API keys must never enter frontend code or browser storage.</div></div>}
        {section === "security" && <div className="space-y-4"><div className="rounded-lg border border-emerald-300/10 bg-emerald-300/[.025] p-4"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-200">Security posture</p><StatusBadge tone="green">Development safe</StatusBadge></div><p className="mt-2 text-xs leading-5 text-slate-500">Administrative actions use local demonstration state. Production deployment requires authenticated routes, role checks, rate limits, CSRF protection, audit persistence, and secret management.</p></div>{["Server-side URL validation", "Private-network target blocking", "Strict content security policy", "Role-based administration", "Persistent audit trail"].map((item, index) => <div key={item} className="flex items-center justify-between rounded-lg border border-white/[.07] p-4"><span className="text-sm text-slate-300">{item}</span><StatusBadge tone={index < 3 ? "green" : "amber"}>{index < 3 ? "designed" : "deployment required"}</StatusBadge></div>)}</div>}
        {section === "data" && <div className="divide-y divide-white/[.06]"><div className="grid gap-4 pb-5 md:grid-cols-2"><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Report retention</span><select className={`${controlClass} w-full`} value={retention} onChange={(event) => setRetention(event.target.value)}><option value="90">90 days</option><option value="180">180 days</option><option value="365">1 year</option><option value="forever">Indefinite</option></select></label><label><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Export format</span><select className={`${controlClass} w-full`} defaultValue="json"><option value="json">JSON with provenance</option><option value="csv">CSV event summary</option><option value="ndjson">NDJSON audit stream</option></select></label></div><Toggle checked={true} onChange={() => undefined} label="Preserve raw payload hashes" description="Retain content hashes and provenance metadata when normalized body text expires." /><div className="py-5"><p className="text-sm font-medium text-red-200">Demonstration data controls</p><p className="mt-1 text-xs leading-5 text-slate-500">Reset local review actions, settings, and collector simulations. The bundled fictional dataset remains available.</p><button type="button" className={`${buttonClass} mt-4 border-red-300/20 text-red-200`} onClick={() => window.location.reload()}>Reset local session</button></div></div>}
      </div>
    </div>
  </section>;
}
