"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { IntelligenceEvent, WatchlistEntry } from "@/packages/shared/types";
import { StatusBadge, buttonClass, controlClass, formatDate, primaryButtonClass, titleCase } from "@/components/domain/argus-ui";

const priorityTone = { critical: "red", high: "amber", medium: "cyan", low: "neutral" } as const;

export function WatchlistConsole({ initialWatchlists, events }: { initialWatchlists: WatchlistEntry[]; events: IntelligenceEvent[] }) {
  const [watchlists, setWatchlists] = useState(initialWatchlists);
  const [selectedId, setSelectedId] = useState(initialWatchlists[0]?.id ?? "");
  const [query, setQuery] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [notice, setNotice] = useState("");
  const [newName, setNewName] = useState("");
  const [newType, setNewType] = useState<WatchlistEntry["type"]>("keyword");

  const filtered = useMemo(() => watchlists.filter((item) => !query.trim() || `${item.name} ${item.type} ${item.notes ?? ""}`.toLowerCase().includes(query.toLowerCase())), [query, watchlists]);
  const selected = watchlists.find((item) => item.id === selectedId) ?? filtered[0];
  const matchedEvents = selected ? events.filter((event) => selected.matchedEventIds.includes(event.id) || event.watchlistIds.includes(selected.id)) : [];

  function createWatchlist(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!newName.trim()) return;
    setNotice(`Draft watchlist “${newName.trim()}” validated locally. Persistence is disabled in demonstration mode.`);
    setShowCreate(false); setNewName("");
  }

  return (
    <>
      <section className="watchlist-layout grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,.8fr)]">
        <div className="overflow-hidden rounded-xl border border-white/10 bg-[#101820]/90">
          <div className="grid gap-3 border-b border-white/[.08] p-3 md:grid-cols-[1fr_auto]"><label className="relative"><span className="sr-only">Search watchlists</span><input className={`${controlClass} w-full pl-9`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search watchlists…" /><span className="absolute left-3 top-2.5 text-slate-500">⌕</span></label><button type="button" className={primaryButtonClass} onClick={() => setShowCreate(true)}>＋ New watchlist</button></div>
          {notice && <p className="border-b border-cyan-300/10 bg-cyan-300/[.035] px-4 py-3 text-[10px] text-cyan-100/70" role="status">{notice}</p>}
          <div className="overflow-x-auto"><table className="data-table w-full min-w-[780px] text-left"><thead><tr className="border-b border-white/[.08] text-[9px] font-bold uppercase tracking-[.14em] text-slate-500"><th className="px-4 py-3">Watchlist</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Rule</th><th className="px-4 py-3">Matches</th><th className="px-4 py-3">Notify</th><th className="px-4 py-3">Enabled</th></tr></thead><tbody className="divide-y divide-white/[.06]">{filtered.map((item) => <tr key={item.id} className={`cursor-pointer transition ${selected?.id === item.id ? "bg-cyan-300/[.04]" : "hover:bg-white/[.018]"}`} onClick={() => setSelectedId(item.id)}><td className="px-4 py-4"><button type="button" className="text-left"><p className="text-sm font-semibold text-slate-200">{item.name}</p><p className="mt-1 text-[10px] text-slate-500">{titleCase(item.type)} · {item.notes ?? "No analyst notes"}</p></button></td><td className="px-4 py-4"><StatusBadge tone={priorityTone[item.priority]}>{item.priority}</StatusBadge></td><td className="px-4 py-4"><p className="max-w-48 text-[10px] leading-4 text-slate-400">{item.matchRules.map((rule) => `${titleCase(rule.field)} ${rule.operator}`).join(" + ")}</p></td><td className="px-4 py-4"><p className="font-mono text-sm text-slate-200">{item.matchCount}</p><p className="mt-1 whitespace-nowrap text-[9px] text-slate-600">{item.lastMatchAt ? formatDate(item.lastMatchAt) : "No match yet"}</p></td><td className="px-4 py-4"><p className="text-[10px] text-slate-300">{titleCase(item.notificationSettings.digest)}</p><p className="mt-1 text-[9px] text-slate-600">S{item.notificationSettings.minimumSeverity}+ · {item.notificationSettings.minimumConfidence}%+</p></td><td className="px-4 py-4"><button type="button" role="switch" aria-checked={item.enabled} aria-label={`${item.enabled ? "Disable" : "Enable"} ${item.name}`} className={`relative h-6 w-11 rounded-full ${item.enabled ? "bg-cyan-300/30" : "bg-slate-700"}`} onClick={(event) => { event.stopPropagation(); setWatchlists((current) => current.map((entry) => entry.id === item.id ? { ...entry, enabled: !entry.enabled } : entry)); }}><span className={`absolute top-1 h-4 w-4 rounded-full bg-slate-100 transition ${item.enabled ? "left-6" : "left-1"}`} /></button></td></tr>)}</tbody></table></div>
        </div>

        <aside className="overflow-hidden rounded-xl border border-white/10 bg-[#0f1821]">
          {selected ? <><div className="border-b border-white/[.08] p-5"><div className="flex items-center justify-between gap-3"><StatusBadge tone={priorityTone[selected.priority]}>{selected.priority} priority</StatusBadge><span className={`h-2 w-2 rounded-full ${selected.enabled ? "bg-emerald-400" : "bg-slate-600"}`} /></div><h2 className="mt-4 text-lg font-semibold text-slate-100">{selected.name}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{selected.notes ?? "No analyst notes are attached to this watchlist."}</p></div><div className="space-y-5 p-5"><section><p className="text-[9px] font-bold uppercase tracking-[.15em] text-slate-500">Match logic</p><div className="mt-3 space-y-2">{selected.matchRules.map((rule, index) => <div key={`${rule.field}-${index}`} className="rounded-lg border border-white/[.07] bg-white/[.018] p-3"><p className="text-xs text-slate-300"><span className="text-cyan-200">{titleCase(rule.field)}</span> {rule.operator}</p><p className="mt-1 break-words font-mono text-[9px] text-slate-600">{typeof rule.value === "object" ? JSON.stringify(rule.value) : rule.value}</p></div>)}</div></section><section><div className="flex items-center justify-between"><p className="text-[9px] font-bold uppercase tracking-[.15em] text-slate-500">Recent alert matches</p><span className="font-mono text-[9px] text-slate-600">{matchedEvents.length}</span></div><div className="mt-3 space-y-2">{matchedEvents.slice(0, 5).map((event) => <Link key={event.id} href={`/events/${event.slug}`} className="block rounded-lg border border-white/[.07] p-3 transition hover:border-cyan-300/20"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold leading-5 text-slate-200">{event.title}</p><span className={`h-2 w-2 shrink-0 rounded-full ${event.severity >= 5 ? "bg-red-400" : event.severity === 4 ? "bg-orange-400" : "bg-cyan-300"}`} /></div><p className="mt-1 text-[9px] text-slate-600">S{event.severity} · {event.automatedConfidence}% confidence · {event.locationName ?? event.countryName}</p></Link>)}{matchedEvents.length === 0 && <p className="rounded border border-dashed border-white/[.08] p-5 text-center text-xs text-slate-600">No current event matches.</p>}</div></section></div><div className="flex gap-2 border-t border-white/[.08] p-4"><button type="button" className={`${buttonClass} flex-1`} onClick={() => setNotice(`${selected.name} rule editor opened in demonstration mode.`)}>Edit rules</button><button type="button" className={`${buttonClass} flex-1`} onClick={() => setNotice(`Notification test for ${selected.name} delivered to the local alert center.`)}>Test alert</button></div></> : <div className="p-10 text-center text-sm text-slate-500">Select a watchlist.</div>}
        </aside>
      </section>

      {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="presentation"><form className="w-full max-w-md rounded-xl border border-white/10 bg-[#111b24] p-5 shadow-2xl" onSubmit={createWatchlist}><p className="text-[9px] uppercase tracking-[.15em] text-cyan-300/70">New monitor</p><h2 className="mt-1 text-lg font-semibold text-slate-100">Create watchlist</h2><label className="mt-5 block"><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Name</span><input autoFocus required className={`${controlClass} w-full`} value={newName} onChange={(event) => setNewName(event.target.value)} placeholder="Port infrastructure risk" /></label><label className="mt-4 block"><span className="mb-2 block text-[10px] uppercase tracking-[.13em] text-slate-500">Monitor type</span><select className={`${controlClass} w-full`} value={newType} onChange={(event) => setNewType(event.target.value as WatchlistEntry["type"])}><option value="keyword">Keyword</option><option value="country">Country</option><option value="region">Region</option><option value="organization">Organization</option><option value="vulnerability">Vulnerability</option><option value="geographic-area">Geographic area</option><option value="event-category">Event category</option></select></label><p className="mt-4 text-xs leading-5 text-slate-500">A draft rule will require analyst review before it becomes an active alert source.</p><div className="mt-5 flex justify-end gap-2 border-t border-white/[.07] pt-4"><button type="button" className={buttonClass} onClick={() => setShowCreate(false)}>Cancel</button><button type="submit" className={primaryButtonClass}>Create draft</button></div></form></div>}
    </>
  );
}
