import { DemoBanner, MetricCard, PageHeader, PanelHeader, StatusBadge, formatDate, panelClass, titleCase } from "@/components/domain/argus-ui";
import { demoCollectorRuns, demoMetrics, demoSources } from "@/packages/shared/demo-data";

export default function SystemPage() {
  const successfulRuns = demoCollectorRuns.filter((run) => run.status === "succeeded").length;
  const statusTone = (status: string): "green" | "amber" | "red" | "neutral" => status === "operational" || status === "online" || status === "succeeded" ? "green" : status === "degraded" || status === "partial" || status === "running" ? "amber" : status === "maintenance" || status === "paused" ? "neutral" : "red";
  return <main className="route-page page-stack space-y-5 p-4 sm:p-6 xl:p-8"><DemoBanner /><PageHeader eyebrow="Platform telemetry / 08" title="System status" description="Inspect collection health, worker throughput, persistence, backlog, latency, source failures, and recent run outcomes from one operational view." actions={<><StatusBadge tone={demoMetrics.workerStatus === "operational" ? "green" : "amber"}>Worker {demoMetrics.workerStatus}</StatusBadge><StatusBadge tone={demoMetrics.databaseStatus === "operational" ? "green" : "red"}>Database {demoMetrics.databaseStatus}</StatusBadge></>} />
    <section className="metric-grid grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-6"><MetricCard label="API response" value={`${demoMetrics.averageApiResponseMs} ms`} detail="Average across services" tone="green" /><MetricCard label="Processing backlog" value={demoMetrics.processingBacklog} detail="Pending pipeline stages" tone={demoMetrics.processingBacklog > 20 ? "amber" : "green"} /><MetricCard label="Sources online" value={`${demoMetrics.sourcesOnline}/${demoMetrics.sourcesTotal}`} detail={`${demoMetrics.failedSources} failed`} tone={demoMetrics.failedSources ? "amber" : "green"} /><MetricCard label="Awaiting processing" value={demoMetrics.reportsAwaitingProcessing} detail="Validated incoming reports" /><MetricCard label="Collector runs" value={demoCollectorRuns.length} detail={`${successfulRuns} successful`} /><MetricCard label="Last ingestion" value={formatDate(demoMetrics.lastSuccessfulIngestionAt).split(",")[0]} detail={formatDate(demoMetrics.lastSuccessfulIngestionAt)} tone="green" /></section>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_380px]">
      <section className={panelClass}><PanelHeader eyebrow="Service matrix" title="Component health" action={<span className="text-[9px] uppercase tracking-[.13em] text-slate-600">Snapshot {formatDate(demoMetrics.generatedAt)}</span>} /><div className="grid gap-3 p-4 md:grid-cols-2">{demoMetrics.componentHealth.map((component) => <article key={component.id} className="rounded-lg border border-white/[.07] bg-white/[.015] p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${component.status === "operational" ? "bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.5)]" : component.status === "degraded" ? "bg-amber-300" : component.status === "maintenance" ? "bg-slate-500" : "bg-red-400"}`} /><div><h3 className="text-sm font-semibold text-slate-200">{component.name}</h3><p className="mt-1 text-[9px] uppercase tracking-[.12em] text-slate-600">{component.id}</p></div></div><StatusBadge tone={statusTone(component.status)}>{component.status}</StatusBadge></div><p className="mt-4 text-xs leading-5 text-slate-500">{component.message}</p><dl className="mt-4 grid grid-cols-3 gap-2 border-t border-white/[.06] pt-3"><div><dt className="text-[8px] uppercase tracking-[.12em] text-slate-600">Latency</dt><dd className="mt-1 font-mono text-[10px] text-slate-300">{component.latencyMs ?? "—"} ms</dd></div><div><dt className="text-[8px] uppercase tracking-[.12em] text-slate-600">Backlog</dt><dd className="mt-1 font-mono text-[10px] text-slate-300">{component.backlog ?? "—"}</dd></div><div><dt className="text-[8px] uppercase tracking-[.12em] text-slate-600">Last success</dt><dd className="mt-1 text-[9px] text-slate-300">{component.lastSuccessfulAt ? formatDate(component.lastSuccessfulAt).split(",")[0] : "—"}</dd></div></dl></article>)}</div></section>
      <section className={panelClass}><PanelHeader eyebrow="Collection edge" title="Source availability" /><div className="divide-y divide-white/[.055]">{demoSources.map((source) => <div key={source.id} className="flex items-center gap-3 px-4 py-3"><span className={`h-2 w-2 rounded-full ${source.status === "online" ? "bg-emerald-400" : source.status === "degraded" ? "bg-amber-300" : source.status === "paused" ? "bg-slate-500" : "bg-red-400"}`} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-slate-300">{source.name}</p><p className="mt-0.5 text-[9px] text-slate-600">{source.schedule.label} · {source.recentFailureCount} failures</p></div><span className="font-mono text-[9px] text-slate-600">{source.reliabilityScore}</span></div>)}</div></section>
    </div>
    <section className={panelClass}><PanelHeader eyebrow="Job telemetry" title="Recent collector runs" /><div className="overflow-x-auto"><table className="data-table w-full min-w-[940px] text-left"><thead><tr className="border-b border-white/[.08] text-[9px] uppercase tracking-[.14em] text-slate-500"><th className="px-4 py-3">Run</th><th className="px-4 py-3">Collector</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Started</th><th className="px-4 py-3">Seen / inserted</th><th className="px-4 py-3">Duplicates</th><th className="px-4 py-3">Retries</th><th className="px-4 py-3">Duration</th></tr></thead><tbody className="divide-y divide-white/[.06]">{demoCollectorRuns.map((run) => <tr key={run.id}><td className="px-4 py-4 font-mono text-[9px] text-slate-600">{run.id.toUpperCase()}</td><td className="px-4 py-4 text-xs text-slate-300">{run.collectorId}</td><td className="px-4 py-4"><StatusBadge tone={statusTone(run.status)}>{titleCase(run.status)}</StatusBadge></td><td className="px-4 py-4 text-[10px] text-slate-500">{formatDate(run.startedAt)}</td><td className="px-4 py-4 font-mono text-xs text-slate-300">{run.reportsSeen} / {run.reportsInserted}</td><td className="px-4 py-4 font-mono text-xs text-slate-400">{run.duplicatesSkipped}</td><td className="px-4 py-4 font-mono text-xs text-slate-400">{run.retryCount}</td><td className="px-4 py-4 font-mono text-xs text-slate-400">{run.durationMs ? `${run.durationMs} ms` : "—"}</td></tr>)}</tbody></table></div></section>
  </main>;
}
